// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutterxel.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterxelBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterxelBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterxelBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int flutterxel_core_version_major() {
    return _flutterxel_core_version_major();
  }

  late final _flutterxel_core_version_majorPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'flutterxel_core_version_major',
      );
  late final _flutterxel_core_version_major = _flutterxel_core_version_majorPtr
      .asFunction<int Function()>();

  int flutterxel_core_version_minor() {
    return _flutterxel_core_version_minor();
  }

  late final _flutterxel_core_version_minorPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'flutterxel_core_version_minor',
      );
  late final _flutterxel_core_version_minor = _flutterxel_core_version_minorPtr
      .asFunction<int Function()>();

  int flutterxel_core_version_patch() {
    return _flutterxel_core_version_patch();
  }

  late final _flutterxel_core_version_patchPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'flutterxel_core_version_patch',
      );
  late final _flutterxel_core_version_patch = _flutterxel_core_version_patchPtr
      .asFunction<int Function()>();

  int flutterxel_core_backend_kind() {
    return _flutterxel_core_backend_kind();
  }

  late final _flutterxel_core_backend_kindPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'flutterxel_core_backend_kind',
      );
  late final _flutterxel_core_backend_kind = _flutterxel_core_backend_kindPtr
      .asFunction<int Function()>();

  bool flutterxel_core_set_num_colors(int num_colors) {
    return _flutterxel_core_set_num_colors(num_colors);
  }

  late final _flutterxel_core_set_num_colorsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_set_num_colors',
      );
  late final _flutterxel_core_set_num_colors =
      _flutterxel_core_set_num_colorsPtr.asFunction<bool Function(int)>();

  int flutterxel_core_num_colors() {
    return _flutterxel_core_num_colors();
  }

  late final _flutterxel_core_num_colorsPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'flutterxel_core_num_colors',
      );
  late final _flutterxel_core_num_colors = _flutterxel_core_num_colorsPtr
      .asFunction<int Function()>();

  bool flutterxel_core_init(
    int width,
    int height,
    ffi.Pointer<ffi.Char> title,
    int fps,
    int quit_key,
    int display_scale,
    int capture_scale,
    int capture_sec,
  ) {
    return _flutterxel_core_init(
      width,
      height,
      title,
      fps,
      quit_key,
      display_scale,
      capture_scale,
      capture_sec,
    );
  }

  late final _flutterxel_core_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_init');
  late final _flutterxel_core_init = _flutterxel_core_initPtr
      .asFunction<
        bool Function(int, int, ffi.Pointer<ffi.Char>, int, int, int, int, int)
      >();

  bool flutterxel_core_quit() {
    return _flutterxel_core_quit();
  }

  late final _flutterxel_core_quitPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('flutterxel_core_quit');
  late final _flutterxel_core_quit = _flutterxel_core_quitPtr
      .asFunction<bool Function()>();

  bool flutterxel_core_run(
    FlutterxelCoreFrameCallback update,
    ffi.Pointer<ffi.Void> update_user_data,
    FlutterxelCoreFrameCallback draw,
    ffi.Pointer<ffi.Void> draw_user_data,
  ) {
    return _flutterxel_core_run(update, update_user_data, draw, draw_user_data);
  }

  late final _flutterxel_core_runPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            FlutterxelCoreFrameCallback,
            ffi.Pointer<ffi.Void>,
            FlutterxelCoreFrameCallback,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('flutterxel_core_run');
  late final _flutterxel_core_run = _flutterxel_core_runPtr
      .asFunction<
        bool Function(
          FlutterxelCoreFrameCallback,
          ffi.Pointer<ffi.Void>,
          FlutterxelCoreFrameCallback,
          ffi.Pointer<ffi.Void>,
        )
      >();

  bool flutterxel_core_flip() {
    return _flutterxel_core_flip();
  }

  late final _flutterxel_core_flipPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('flutterxel_core_flip');
  late final _flutterxel_core_flip = _flutterxel_core_flipPtr
      .asFunction<bool Function()>();

  bool flutterxel_core_show() {
    return _flutterxel_core_show();
  }

  late final _flutterxel_core_showPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('flutterxel_core_show');
  late final _flutterxel_core_show = _flutterxel_core_showPtr
      .asFunction<bool Function()>();

  bool flutterxel_core_title(ffi.Pointer<ffi.Char> title) {
    return _flutterxel_core_title(title);
  }

  late final _flutterxel_core_titlePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'flutterxel_core_title',
      );
  late final _flutterxel_core_title = _flutterxel_core_titlePtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  bool flutterxel_core_icon(ffi.Pointer<ffi.Char> data, int scale, int colkey) {
    return _flutterxel_core_icon(data, scale, colkey);
  }

  late final _flutterxel_core_iconPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Int32, ffi.Int32)
        >
      >('flutterxel_core_icon');
  late final _flutterxel_core_icon = _flutterxel_core_iconPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>, int, int)>();

  bool flutterxel_core_reset() {
    return _flutterxel_core_reset();
  }

  late final _flutterxel_core_resetPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('flutterxel_core_reset');
  late final _flutterxel_core_reset = _flutterxel_core_resetPtr
      .asFunction<bool Function()>();

  bool flutterxel_core_perf_monitor(bool enabled) {
    return _flutterxel_core_perf_monitor(enabled);
  }

  late final _flutterxel_core_perf_monitorPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Bool)>>(
        'flutterxel_core_perf_monitor',
      );
  late final _flutterxel_core_perf_monitor = _flutterxel_core_perf_monitorPtr
      .asFunction<bool Function(bool)>();

  bool flutterxel_core_integer_scale(bool enabled) {
    return _flutterxel_core_integer_scale(enabled);
  }

  late final _flutterxel_core_integer_scalePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Bool)>>(
        'flutterxel_core_integer_scale',
      );
  late final _flutterxel_core_integer_scale = _flutterxel_core_integer_scalePtr
      .asFunction<bool Function(bool)>();

  bool flutterxel_core_screen_mode(int scr) {
    return _flutterxel_core_screen_mode(scr);
  }

  late final _flutterxel_core_screen_modePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_screen_mode',
      );
  late final _flutterxel_core_screen_mode = _flutterxel_core_screen_modePtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_fullscreen(bool enabled) {
    return _flutterxel_core_fullscreen(enabled);
  }

  late final _flutterxel_core_fullscreenPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Bool)>>(
        'flutterxel_core_fullscreen',
      );
  late final _flutterxel_core_fullscreen = _flutterxel_core_fullscreenPtr
      .asFunction<bool Function(bool)>();

  int flutterxel_core_frame_count() {
    return _flutterxel_core_frame_count();
  }

  late final _flutterxel_core_frame_countPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>(
        'flutterxel_core_frame_count',
      );
  late final _flutterxel_core_frame_count = _flutterxel_core_frame_countPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Int32> flutterxel_core_framebuffer_ptr() {
    return _flutterxel_core_framebuffer_ptr();
  }

  late final _flutterxel_core_framebuffer_ptrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function()>>(
        'flutterxel_core_framebuffer_ptr',
      );
  late final _flutterxel_core_framebuffer_ptr =
      _flutterxel_core_framebuffer_ptrPtr
          .asFunction<ffi.Pointer<ffi.Int32> Function()>();

  int flutterxel_core_framebuffer_len() {
    return _flutterxel_core_framebuffer_len();
  }

  late final _flutterxel_core_framebuffer_lenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        'flutterxel_core_framebuffer_len',
      );
  late final _flutterxel_core_framebuffer_len =
      _flutterxel_core_framebuffer_lenPtr.asFunction<int Function()>();

  bool flutterxel_core_copy_framebuffer(
    ffi.Pointer<ffi.Int32> dst,
    int dst_len,
  ) {
    return _flutterxel_core_copy_framebuffer(dst, dst_len);
  }

  late final _flutterxel_core_copy_framebufferPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Int32>, ffi.Size)>
      >('flutterxel_core_copy_framebuffer');
  late final _flutterxel_core_copy_framebuffer =
      _flutterxel_core_copy_framebufferPtr
          .asFunction<bool Function(ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_btn(int key) {
    return _flutterxel_core_btn(key);
  }

  late final _flutterxel_core_btnPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_btn',
      );
  late final _flutterxel_core_btn = _flutterxel_core_btnPtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_btnp(int key, int hold, int period) {
    return _flutterxel_core_btnp(key, hold, period);
  }

  late final _flutterxel_core_btnpPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32)>
      >('flutterxel_core_btnp');
  late final _flutterxel_core_btnp = _flutterxel_core_btnpPtr
      .asFunction<bool Function(int, int, int)>();

  bool flutterxel_core_btnr(int key) {
    return _flutterxel_core_btnr(key);
  }

  late final _flutterxel_core_btnrPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_btnr',
      );
  late final _flutterxel_core_btnr = _flutterxel_core_btnrPtr
      .asFunction<bool Function(int)>();

  int flutterxel_core_btnv(int key) {
    return _flutterxel_core_btnv(key);
  }

  late final _flutterxel_core_btnvPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32)>>(
        'flutterxel_core_btnv',
      );
  late final _flutterxel_core_btnv = _flutterxel_core_btnvPtr
      .asFunction<int Function(int)>();

  bool flutterxel_core_mouse(bool visible) {
    return _flutterxel_core_mouse(visible);
  }

  late final _flutterxel_core_mousePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Bool)>>(
        'flutterxel_core_mouse',
      );
  late final _flutterxel_core_mouse = _flutterxel_core_mousePtr
      .asFunction<bool Function(bool)>();

  bool flutterxel_core_warp_mouse(double x, double y) {
    return _flutterxel_core_warp_mouse(x, y);
  }

  late final _flutterxel_core_warp_mousePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Double, ffi.Double)>>(
        'flutterxel_core_warp_mouse',
      );
  late final _flutterxel_core_warp_mouse = _flutterxel_core_warp_mousePtr
      .asFunction<bool Function(double, double)>();

  bool flutterxel_core_set_btn_state(int key, bool pressed) {
    return _flutterxel_core_set_btn_state(key, pressed);
  }

  late final _flutterxel_core_set_btn_statePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Bool)>>(
        'flutterxel_core_set_btn_state',
      );
  late final _flutterxel_core_set_btn_state = _flutterxel_core_set_btn_statePtr
      .asFunction<bool Function(int, bool)>();

  bool flutterxel_core_set_btn_value(int key, int value) {
    return _flutterxel_core_set_btn_value(key, value);
  }

  late final _flutterxel_core_set_btn_valuePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_set_btn_value',
      );
  late final _flutterxel_core_set_btn_value = _flutterxel_core_set_btn_valuePtr
      .asFunction<bool Function(int, int)>();

  bool flutterxel_core_cls(int col) {
    return _flutterxel_core_cls(col);
  }

  late final _flutterxel_core_clsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_cls',
      );
  late final _flutterxel_core_cls = _flutterxel_core_clsPtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_camera(int x, int y) {
    return _flutterxel_core_camera(x, y);
  }

  late final _flutterxel_core_cameraPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_camera',
      );
  late final _flutterxel_core_camera = _flutterxel_core_cameraPtr
      .asFunction<bool Function(int, int)>();

  bool flutterxel_core_clip(int x, int y, int w, int h) {
    return _flutterxel_core_clip(x, y, w, h);
  }

  late final _flutterxel_core_clipPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32)
        >
      >('flutterxel_core_clip');
  late final _flutterxel_core_clip = _flutterxel_core_clipPtr
      .asFunction<bool Function(int, int, int, int)>();

  bool flutterxel_core_pal(int col1, int col2) {
    return _flutterxel_core_pal(col1, col2);
  }

  late final _flutterxel_core_palPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_pal',
      );
  late final _flutterxel_core_pal = _flutterxel_core_palPtr
      .asFunction<bool Function(int, int)>();

  bool flutterxel_core_dither(double alpha) {
    return _flutterxel_core_dither(alpha);
  }

  late final _flutterxel_core_ditherPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Double)>>(
        'flutterxel_core_dither',
      );
  late final _flutterxel_core_dither = _flutterxel_core_ditherPtr
      .asFunction<bool Function(double)>();

  bool flutterxel_core_pset(int x, int y, int col) {
    return _flutterxel_core_pset(x, y, col);
  }

  late final _flutterxel_core_psetPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32)>
      >('flutterxel_core_pset');
  late final _flutterxel_core_pset = _flutterxel_core_psetPtr
      .asFunction<bool Function(int, int, int)>();

  int flutterxel_core_pget(int x, int y) {
    return _flutterxel_core_pget(x, y);
  }

  late final _flutterxel_core_pgetPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_pget',
      );
  late final _flutterxel_core_pget = _flutterxel_core_pgetPtr
      .asFunction<int Function(int, int)>();

  bool flutterxel_core_line(int x1, int y1, int x2, int y2, int col) {
    return _flutterxel_core_line(x1, y1, x2, y2, col);
  }

  late final _flutterxel_core_linePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_line');
  late final _flutterxel_core_line = _flutterxel_core_linePtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_rect(int x, int y, int w, int h, int col) {
    return _flutterxel_core_rect(x, y, w, h, col);
  }

  late final _flutterxel_core_rectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_rect');
  late final _flutterxel_core_rect = _flutterxel_core_rectPtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_rectb(int x, int y, int w, int h, int col) {
    return _flutterxel_core_rectb(x, y, w, h, col);
  }

  late final _flutterxel_core_rectbPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_rectb');
  late final _flutterxel_core_rectb = _flutterxel_core_rectbPtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_circ(int x, int y, int r, int col) {
    return _flutterxel_core_circ(x, y, r, col);
  }

  late final _flutterxel_core_circPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32)
        >
      >('flutterxel_core_circ');
  late final _flutterxel_core_circ = _flutterxel_core_circPtr
      .asFunction<bool Function(int, int, int, int)>();

  bool flutterxel_core_circb(int x, int y, int r, int col) {
    return _flutterxel_core_circb(x, y, r, col);
  }

  late final _flutterxel_core_circbPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32)
        >
      >('flutterxel_core_circb');
  late final _flutterxel_core_circb = _flutterxel_core_circbPtr
      .asFunction<bool Function(int, int, int, int)>();

  bool flutterxel_core_elli(int x, int y, int w, int h, int col) {
    return _flutterxel_core_elli(x, y, w, h, col);
  }

  late final _flutterxel_core_elliPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_elli');
  late final _flutterxel_core_elli = _flutterxel_core_elliPtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_ellib(int x, int y, int w, int h, int col) {
    return _flutterxel_core_ellib(x, y, w, h, col);
  }

  late final _flutterxel_core_ellibPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_ellib');
  late final _flutterxel_core_ellib = _flutterxel_core_ellibPtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_tri(
    int x1,
    int y1,
    int x2,
    int y2,
    int x3,
    int y3,
    int col,
  ) {
    return _flutterxel_core_tri(x1, y1, x2, y2, x3, y3, col);
  }

  late final _flutterxel_core_triPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_tri');
  late final _flutterxel_core_tri = _flutterxel_core_triPtr
      .asFunction<bool Function(int, int, int, int, int, int, int)>();

  bool flutterxel_core_trib(
    int x1,
    int y1,
    int x2,
    int y2,
    int x3,
    int y3,
    int col,
  ) {
    return _flutterxel_core_trib(x1, y1, x2, y2, x3, y3, col);
  }

  late final _flutterxel_core_tribPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_trib');
  late final _flutterxel_core_trib = _flutterxel_core_tribPtr
      .asFunction<bool Function(int, int, int, int, int, int, int)>();

  bool flutterxel_core_fill(int x, int y, int col) {
    return _flutterxel_core_fill(x, y, col);
  }

  late final _flutterxel_core_fillPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32)>
      >('flutterxel_core_fill');
  late final _flutterxel_core_fill = _flutterxel_core_fillPtr
      .asFunction<bool Function(int, int, int)>();

  bool flutterxel_core_text(int x, int y, ffi.Pointer<ffi.Char> text, int col) {
    return _flutterxel_core_text(x, y, text, col);
  }

  late final _flutterxel_core_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('flutterxel_core_text');
  late final _flutterxel_core_text = _flutterxel_core_textPtr
      .asFunction<bool Function(int, int, ffi.Pointer<ffi.Char>, int)>();

  bool flutterxel_core_bltm(
    double x,
    double y,
    int tm,
    double u,
    double v,
    double w,
    double h,
    int colkey,
  ) {
    return _flutterxel_core_bltm(x, y, tm, u, v, w, h, colkey);
  }

  late final _flutterxel_core_bltmPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Double,
            ffi.Double,
            ffi.Int32,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Int32,
          )
        >
      >('flutterxel_core_bltm');
  late final _flutterxel_core_bltm = _flutterxel_core_bltmPtr
      .asFunction<
        bool Function(double, double, int, double, double, double, double, int)
      >();

  bool flutterxel_core_blt(
    double x,
    double y,
    int img,
    double u,
    double v,
    double w,
    double h,
    int colkey,
    double rotate,
    double scale,
  ) {
    return _flutterxel_core_blt(x, y, img, u, v, w, h, colkey, rotate, scale);
  }

  late final _flutterxel_core_bltPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Double,
            ffi.Double,
            ffi.Int32,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Int32,
            ffi.Double,
            ffi.Double,
          )
        >
      >('flutterxel_core_blt');
  late final _flutterxel_core_blt = _flutterxel_core_bltPtr
      .asFunction<
        bool Function(
          double,
          double,
          int,
          double,
          double,
          double,
          double,
          int,
          double,
          double,
        )
      >();

  bool flutterxel_core_image_pset(int img, int x, int y, int col) {
    return _flutterxel_core_image_pset(img, x, y, col);
  }

  late final _flutterxel_core_image_psetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32)
        >
      >('flutterxel_core_image_pset');
  late final _flutterxel_core_image_pset = _flutterxel_core_image_psetPtr
      .asFunction<bool Function(int, int, int, int)>();

  bool flutterxel_core_image_pget(
    int img,
    int x,
    int y,
    ffi.Pointer<ffi.Int32> col_out,
  ) {
    return _flutterxel_core_image_pget(img, x, y, col_out);
  }

  late final _flutterxel_core_image_pgetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('flutterxel_core_image_pget');
  late final _flutterxel_core_image_pget = _flutterxel_core_image_pgetPtr
      .asFunction<bool Function(int, int, int, ffi.Pointer<ffi.Int32>)>();

  bool flutterxel_core_image_cls(int img, int col) {
    return _flutterxel_core_image_cls(img, col);
  }

  late final _flutterxel_core_image_clsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_image_cls',
      );
  late final _flutterxel_core_image_cls = _flutterxel_core_image_clsPtr
      .asFunction<bool Function(int, int)>();

  bool flutterxel_core_image_replace(
    int img,
    ffi.Pointer<ffi.Int32> data,
    int len,
  ) {
    return _flutterxel_core_image_replace(img, data, len);
  }

  late final _flutterxel_core_image_replacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.Size)
        >
      >('flutterxel_core_image_replace');
  late final _flutterxel_core_image_replace = _flutterxel_core_image_replacePtr
      .asFunction<bool Function(int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_tilemap_pset(
    int tm,
    int x,
    int y,
    int tile_x,
    int tile_y,
  ) {
    return _flutterxel_core_tilemap_pset(tm, x, y, tile_x, tile_y);
  }

  late final _flutterxel_core_tilemap_psetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutterxel_core_tilemap_pset');
  late final _flutterxel_core_tilemap_pset = _flutterxel_core_tilemap_psetPtr
      .asFunction<bool Function(int, int, int, int, int)>();

  bool flutterxel_core_tilemap_pget(
    int tm,
    int x,
    int y,
    ffi.Pointer<ffi.Int32> tile_x_out,
    ffi.Pointer<ffi.Int32> tile_y_out,
  ) {
    return _flutterxel_core_tilemap_pget(tm, x, y, tile_x_out, tile_y_out);
  }

  late final _flutterxel_core_tilemap_pgetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('flutterxel_core_tilemap_pget');
  late final _flutterxel_core_tilemap_pget = _flutterxel_core_tilemap_pgetPtr
      .asFunction<
        bool Function(
          int,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  bool flutterxel_core_tilemap_cls(int tm, int tile_x, int tile_y) {
    return _flutterxel_core_tilemap_cls(tm, tile_x, tile_y);
  }

  late final _flutterxel_core_tilemap_clsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32, ffi.Int32)>
      >('flutterxel_core_tilemap_cls');
  late final _flutterxel_core_tilemap_cls = _flutterxel_core_tilemap_clsPtr
      .asFunction<bool Function(int, int, int)>();

  bool flutterxel_core_tilemap_set_imgsrc(int tm, int imgsrc) {
    return _flutterxel_core_tilemap_set_imgsrc(tm, imgsrc);
  }

  late final _flutterxel_core_tilemap_set_imgsrcPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_tilemap_set_imgsrc',
      );
  late final _flutterxel_core_tilemap_set_imgsrc =
      _flutterxel_core_tilemap_set_imgsrcPtr
          .asFunction<bool Function(int, int)>();

  bool flutterxel_core_sound_set_notes(
    int snd,
    ffi.Pointer<ffi.Int32> notes_ptr,
    int notes_len,
  ) {
    return _flutterxel_core_sound_set_notes(snd, notes_ptr, notes_len);
  }

  late final _flutterxel_core_sound_set_notesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.Size)
        >
      >('flutterxel_core_sound_set_notes');
  late final _flutterxel_core_sound_set_notes =
      _flutterxel_core_sound_set_notesPtr
          .asFunction<bool Function(int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_sound_set_tones(
    int snd,
    ffi.Pointer<ffi.Int32> tones_ptr,
    int tones_len,
  ) {
    return _flutterxel_core_sound_set_tones(snd, tones_ptr, tones_len);
  }

  late final _flutterxel_core_sound_set_tonesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.Size)
        >
      >('flutterxel_core_sound_set_tones');
  late final _flutterxel_core_sound_set_tones =
      _flutterxel_core_sound_set_tonesPtr
          .asFunction<bool Function(int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_sound_set_volumes(
    int snd,
    ffi.Pointer<ffi.Int32> volumes_ptr,
    int volumes_len,
  ) {
    return _flutterxel_core_sound_set_volumes(snd, volumes_ptr, volumes_len);
  }

  late final _flutterxel_core_sound_set_volumesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.Size)
        >
      >('flutterxel_core_sound_set_volumes');
  late final _flutterxel_core_sound_set_volumes =
      _flutterxel_core_sound_set_volumesPtr
          .asFunction<bool Function(int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_sound_set_effects(
    int snd,
    ffi.Pointer<ffi.Int32> effects_ptr,
    int effects_len,
  ) {
    return _flutterxel_core_sound_set_effects(snd, effects_ptr, effects_len);
  }

  late final _flutterxel_core_sound_set_effectsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.Size)
        >
      >('flutterxel_core_sound_set_effects');
  late final _flutterxel_core_sound_set_effects =
      _flutterxel_core_sound_set_effectsPtr
          .asFunction<bool Function(int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_sound_set_speed(int snd, int speed) {
    return _flutterxel_core_sound_set_speed(snd, speed);
  }

  late final _flutterxel_core_sound_set_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_sound_set_speed',
      );
  late final _flutterxel_core_sound_set_speed =
      _flutterxel_core_sound_set_speedPtr.asFunction<bool Function(int, int)>();

  bool flutterxel_core_music_set_seq(
    int msc,
    int ch,
    ffi.Pointer<ffi.Int32> seq_ptr,
    int seq_len,
  ) {
    return _flutterxel_core_music_set_seq(msc, ch, seq_ptr, seq_len);
  }

  late final _flutterxel_core_music_set_seqPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Size,
          )
        >
      >('flutterxel_core_music_set_seq');
  late final _flutterxel_core_music_set_seq = _flutterxel_core_music_set_seqPtr
      .asFunction<bool Function(int, int, ffi.Pointer<ffi.Int32>, int)>();

  bool flutterxel_core_play(
    int ch,
    int snd_kind,
    int snd_value,
    ffi.Pointer<ffi.Int32> snd_sequence_ptr,
    int snd_sequence_len,
    ffi.Pointer<ffi.Char> snd_string,
    double sec,
    int loop,
    int resume,
  ) {
    return _flutterxel_core_play(
      ch,
      snd_kind,
      snd_value,
      snd_sequence_ptr,
      snd_sequence_len,
      snd_string,
      sec,
      loop,
      resume,
    );
  }

  late final _flutterxel_core_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Double,
            ffi.Int8,
            ffi.Int8,
          )
        >
      >('flutterxel_core_play');
  late final _flutterxel_core_play = _flutterxel_core_playPtr
      .asFunction<
        bool Function(
          int,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
          int,
          ffi.Pointer<ffi.Char>,
          double,
          int,
          int,
        )
      >();

  bool flutterxel_core_playm(int msc, bool loop) {
    return _flutterxel_core_playm(msc, loop);
  }

  late final _flutterxel_core_playmPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32, ffi.Bool)>>(
        'flutterxel_core_playm',
      );
  late final _flutterxel_core_playm = _flutterxel_core_playmPtr
      .asFunction<bool Function(int, bool)>();

  bool flutterxel_core_stop(int ch) {
    return _flutterxel_core_stop(ch);
  }

  late final _flutterxel_core_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_stop',
      );
  late final _flutterxel_core_stop = _flutterxel_core_stopPtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_is_channel_playing(int ch) {
    return _flutterxel_core_is_channel_playing(ch);
  }

  late final _flutterxel_core_is_channel_playingPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_is_channel_playing',
      );
  late final _flutterxel_core_is_channel_playing =
      _flutterxel_core_is_channel_playingPtr.asFunction<bool Function(int)>();

  bool flutterxel_core_play_pos(
    int ch,
    ffi.Pointer<ffi.Int32> snd,
    ffi.Pointer<ffi.Double> pos,
  ) {
    return _flutterxel_core_play_pos(ch, snd, pos);
  }

  late final _flutterxel_core_play_posPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Double>,
          )
        >
      >('flutterxel_core_play_pos');
  late final _flutterxel_core_play_pos = _flutterxel_core_play_posPtr
      .asFunction<
        bool Function(int, ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Double>)
      >();

  bool flutterxel_core_rseed(int seed) {
    return _flutterxel_core_rseed(seed);
  }

  late final _flutterxel_core_rseedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_rseed',
      );
  late final _flutterxel_core_rseed = _flutterxel_core_rseedPtr
      .asFunction<bool Function(int)>();

  int flutterxel_core_rndi(int a, int b) {
    return _flutterxel_core_rndi(a, b);
  }

  late final _flutterxel_core_rndiPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>(
        'flutterxel_core_rndi',
      );
  late final _flutterxel_core_rndi = _flutterxel_core_rndiPtr
      .asFunction<int Function(int, int)>();

  double flutterxel_core_rndf(double a, double b) {
    return _flutterxel_core_rndf(a, b);
  }

  late final _flutterxel_core_rndfPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
        'flutterxel_core_rndf',
      );
  late final _flutterxel_core_rndf = _flutterxel_core_rndfPtr
      .asFunction<double Function(double, double)>();

  bool flutterxel_core_nseed(int seed) {
    return _flutterxel_core_nseed(seed);
  }

  late final _flutterxel_core_nseedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_nseed',
      );
  late final _flutterxel_core_nseed = _flutterxel_core_nseedPtr
      .asFunction<bool Function(int)>();

  double flutterxel_core_noise(double x, double y, double z) {
    return _flutterxel_core_noise(x, y, z);
  }

  late final _flutterxel_core_noisePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double, ffi.Double)
        >
      >('flutterxel_core_noise');
  late final _flutterxel_core_noise = _flutterxel_core_noisePtr
      .asFunction<double Function(double, double, double)>();

  int flutterxel_core_ceil(double x) {
    return _flutterxel_core_ceil(x);
  }

  late final _flutterxel_core_ceilPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Double)>>(
        'flutterxel_core_ceil',
      );
  late final _flutterxel_core_ceil = _flutterxel_core_ceilPtr
      .asFunction<int Function(double)>();

  int flutterxel_core_floor(double x) {
    return _flutterxel_core_floor(x);
  }

  late final _flutterxel_core_floorPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Double)>>(
        'flutterxel_core_floor',
      );
  late final _flutterxel_core_floor = _flutterxel_core_floorPtr
      .asFunction<int Function(double)>();

  int flutterxel_core_clamp_i64(int x, int lower, int upper) {
    return _flutterxel_core_clamp_i64(x, lower, upper);
  }

  late final _flutterxel_core_clamp_i64Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Int64)>
      >('flutterxel_core_clamp_i64');
  late final _flutterxel_core_clamp_i64 = _flutterxel_core_clamp_i64Ptr
      .asFunction<int Function(int, int, int)>();

  double flutterxel_core_clamp_f64(double x, double lower, double upper) {
    return _flutterxel_core_clamp_f64(x, lower, upper);
  }

  late final _flutterxel_core_clamp_f64Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double, ffi.Double)
        >
      >('flutterxel_core_clamp_f64');
  late final _flutterxel_core_clamp_f64 = _flutterxel_core_clamp_f64Ptr
      .asFunction<double Function(double, double, double)>();

  int flutterxel_core_sgn_i64(int x) {
    return _flutterxel_core_sgn_i64(x);
  }

  late final _flutterxel_core_sgn_i64Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
        'flutterxel_core_sgn_i64',
      );
  late final _flutterxel_core_sgn_i64 = _flutterxel_core_sgn_i64Ptr
      .asFunction<int Function(int)>();

  double flutterxel_core_sgn_f64(double x) {
    return _flutterxel_core_sgn_f64(x);
  }

  late final _flutterxel_core_sgn_f64Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
        'flutterxel_core_sgn_f64',
      );
  late final _flutterxel_core_sgn_f64 = _flutterxel_core_sgn_f64Ptr
      .asFunction<double Function(double)>();

  double flutterxel_core_sqrt(double x) {
    return _flutterxel_core_sqrt(x);
  }

  late final _flutterxel_core_sqrtPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
        'flutterxel_core_sqrt',
      );
  late final _flutterxel_core_sqrt = _flutterxel_core_sqrtPtr
      .asFunction<double Function(double)>();

  double flutterxel_core_sin(double deg) {
    return _flutterxel_core_sin(deg);
  }

  late final _flutterxel_core_sinPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
        'flutterxel_core_sin',
      );
  late final _flutterxel_core_sin = _flutterxel_core_sinPtr
      .asFunction<double Function(double)>();

  double flutterxel_core_cos(double deg) {
    return _flutterxel_core_cos(deg);
  }

  late final _flutterxel_core_cosPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
        'flutterxel_core_cos',
      );
  late final _flutterxel_core_cos = _flutterxel_core_cosPtr
      .asFunction<double Function(double)>();

  double flutterxel_core_atan2(double y, double x) {
    return _flutterxel_core_atan2(y, x);
  }

  late final _flutterxel_core_atan2Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
        'flutterxel_core_atan2',
      );
  late final _flutterxel_core_atan2 = _flutterxel_core_atan2Ptr
      .asFunction<double Function(double, double)>();

  bool flutterxel_core_load(
    ffi.Pointer<ffi.Char> filename,
    int exclude_images,
    int exclude_tilemaps,
    int exclude_sounds,
    int exclude_musics,
  ) {
    return _flutterxel_core_load(
      filename,
      exclude_images,
      exclude_tilemaps,
      exclude_sounds,
      exclude_musics,
    );
  }

  late final _flutterxel_core_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int8,
            ffi.Int8,
            ffi.Int8,
            ffi.Int8,
          )
        >
      >('flutterxel_core_load');
  late final _flutterxel_core_load = _flutterxel_core_loadPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>, int, int, int, int)>();

  bool flutterxel_core_save(
    ffi.Pointer<ffi.Char> filename,
    int exclude_images,
    int exclude_tilemaps,
    int exclude_sounds,
    int exclude_musics,
  ) {
    return _flutterxel_core_save(
      filename,
      exclude_images,
      exclude_tilemaps,
      exclude_sounds,
      exclude_musics,
    );
  }

  late final _flutterxel_core_savePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int8,
            ffi.Int8,
            ffi.Int8,
            ffi.Int8,
          )
        >
      >('flutterxel_core_save');
  late final _flutterxel_core_save = _flutterxel_core_savePtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>, int, int, int, int)>();

  bool flutterxel_core_load_pal(ffi.Pointer<ffi.Char> filename) {
    return _flutterxel_core_load_pal(filename);
  }

  late final _flutterxel_core_load_palPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'flutterxel_core_load_pal',
      );
  late final _flutterxel_core_load_pal = _flutterxel_core_load_palPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  bool flutterxel_core_save_pal(ffi.Pointer<ffi.Char> filename) {
    return _flutterxel_core_save_pal(filename);
  }

  late final _flutterxel_core_save_palPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'flutterxel_core_save_pal',
      );
  late final _flutterxel_core_save_pal = _flutterxel_core_save_palPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  bool flutterxel_core_screenshot(int scale) {
    return _flutterxel_core_screenshot(scale);
  }

  late final _flutterxel_core_screenshotPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_screenshot',
      );
  late final _flutterxel_core_screenshot = _flutterxel_core_screenshotPtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_screencast(int scale) {
    return _flutterxel_core_screencast(scale);
  }

  late final _flutterxel_core_screencastPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int32)>>(
        'flutterxel_core_screencast',
      );
  late final _flutterxel_core_screencast = _flutterxel_core_screencastPtr
      .asFunction<bool Function(int)>();

  bool flutterxel_core_reset_screencast() {
    return _flutterxel_core_reset_screencast();
  }

  late final _flutterxel_core_reset_screencastPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'flutterxel_core_reset_screencast',
      );
  late final _flutterxel_core_reset_screencast =
      _flutterxel_core_reset_screencastPtr.asFunction<bool Function()>();
}

/// Optional parameter encoding in ABI:
/// - optional int32: INT32_MIN means None
/// - optional float64: NaN means None
/// - optional bool: -1 means None, 0 means false, 1 means true
enum FlutterxelCorePlaySndKind {
  FLUTTERXEL_CORE_PLAY_SND_INT(0),
  FLUTTERXEL_CORE_PLAY_SND_INT_LIST(1),
  FLUTTERXEL_CORE_PLAY_SND_STRING(2);

  final int value;
  const FlutterxelCorePlaySndKind(this.value);

  static FlutterxelCorePlaySndKind fromValue(int value) => switch (value) {
    0 => FLUTTERXEL_CORE_PLAY_SND_INT,
    1 => FLUTTERXEL_CORE_PLAY_SND_INT_LIST,
    2 => FLUTTERXEL_CORE_PLAY_SND_STRING,
    _ => throw ArgumentError(
      "Unknown value for FlutterxelCorePlaySndKind: $value",
    ),
  };
}

enum FlutterxelCoreBackendKind {
  FLUTTERXEL_CORE_BACKEND_NATIVE_CORE(1),
  FLUTTERXEL_CORE_BACKEND_C_FALLBACK(2),
  FLUTTERXEL_CORE_BACKEND_DART_FALLBACK(3);

  final int value;
  const FlutterxelCoreBackendKind(this.value);

  static FlutterxelCoreBackendKind fromValue(int value) => switch (value) {
    1 => FLUTTERXEL_CORE_BACKEND_NATIVE_CORE,
    2 => FLUTTERXEL_CORE_BACKEND_C_FALLBACK,
    3 => FLUTTERXEL_CORE_BACKEND_DART_FALLBACK,
    _ => throw ArgumentError(
      "Unknown value for FlutterxelCoreBackendKind: $value",
    ),
  };
}

typedef FlutterxelCoreFrameCallback =
    ffi.Pointer<ffi.NativeFunction<FlutterxelCoreFrameCallbackFunction>>;
typedef FlutterxelCoreFrameCallbackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartFlutterxelCoreFrameCallbackFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);
